webtalk_init -webtalk_dir C:/Users/SET253-08U.HCCMAIN/Documents/GitHub/ENES247_TRUC/lab7-Behavioral-Modeling/lab7_1_1/7_1_1/7_1_1.sim/sim_1/behav/xsim/xsim.dir/lab7_1_1_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Apr 12 14:13:38 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4d37c493-38a8-48a6-98c2-074d97c8e3dc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "86445bf1600242dba210fdb44c8fefad" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6152_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1484495683 -regid "" -xml C:/Users/SET253-08U.HCCMAIN/Documents/GitHub/ENES247_TRUC/lab7-Behavioral-Modeling/lab7_1_1/7_1_1/7_1_1.sim/sim_1/behav/xsim/xsim.dir/lab7_1_1_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/SET253-08U.HCCMAIN/Documents/GitHub/ENES247_TRUC/lab7-Behavioral-Modeling/lab7_1_1/7_1_1/7_1_1.sim/sim_1/behav/xsim/xsim.dir/lab7_1_1_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/SET253-08U.HCCMAIN/Documents/GitHub/ENES247_TRUC/lab7-Behavioral-Modeling/lab7_1_1/7_1_1/7_1_1.sim/sim_1/behav/xsim/xsim.dir/lab7_1_1_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
