# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/SET253-21U.HCCMAIN/Documents/GitHub/ENES247_TRUC/lab8-IntellectualProperty/project_1/project_1.srcs/sources_1/ip/four_bit_counter_fabric/four_bit_counter_fabric.xci
# IP: The module: 'four_bit_counter_fabric' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SET253-21U.HCCMAIN/Documents/GitHub/ENES247_TRUC/lab8-IntellectualProperty/project_1/project_1.srcs/sources_1/ip/four_bit_counter_fabric/four_bit_counter_fabric_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'four_bit_counter_fabric'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/SET253-21U.HCCMAIN/Documents/GitHub/ENES247_TRUC/lab8-IntellectualProperty/project_1/project_1.srcs/sources_1/ip/four_bit_counter_fabric/four_bit_counter_fabric.xci
# IP: The module: 'four_bit_counter_fabric' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SET253-21U.HCCMAIN/Documents/GitHub/ENES247_TRUC/lab8-IntellectualProperty/project_1/project_1.srcs/sources_1/ip/four_bit_counter_fabric/four_bit_counter_fabric_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'four_bit_counter_fabric'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
